volumes:
  db-data:

services:
  db:
    image: groonga/pgroonga:latest
    container_name: meshipiyo
    volumes:
      - db-data:/var/lib/postgresql/meshipiyo/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: backend
    ports:
      - "4000:4000"
    env_file:
      - ./apps/backend/.env
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
