version: "3"

volumes:
  db-data:

services:
  db:
    image: postgres:15
    container_name: sample-monorepo-pnpm
    volumes:
      - db-data:/var/lib/postgresql/sample-monorepo-pnpm/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
