name: PR
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Display the path
        shell: bash
        run: echo $PATH
